2024-10-20 18:11:03,869 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Users\User\Programming\PYTHON\Projects\Modul_12\homeworks\module_12_4_tests.py", line 20, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "D:\Users\User\Programming\PYTHON\Projects\Modul_12\homeworks\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-20 18:11:03,874 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Users\User\Programming\PYTHON\Projects\Modul_12\homeworks\module_12_4_tests.py", line 9, in test_walk
    runner = Runner('Turtle', -5)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\User\Programming\PYTHON\Projects\Modul_12\homeworks\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
